### ISSUE TITLE
Why does this repository exist?

### ISSUE THREAD

**Issue by zednis** [tetherless-world/twcJul2015#1]

**Comment by stephentmoon** [comment]
John created the repository so we could put the statistical queries online
so that we could easily insert the link on the DCO test portal.

On Fri, Jul 17, 2015 at 1:59 PM, Stephan Zednik notifications@github.com
wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/tetherless-world/twcJul2015/issues/1.

## 

Stephen T. Moon
(860) 480-8751

**Comment by mrpatrickwest** [comment]
This is okay for now. Keep working on the query and xslt files. Use the git command line or client tool.

**Comment by olyerickson** [comment]
Because I want it to

On Fri, Jul 17, 2015 at 1:59 PM, Stephan Zednik notifications@github.com
wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/tetherless-world/twcJul2015/issues/1.

## 

John S. Erickson, Ph.D.
Director of Operations, The Rensselaer IDEA
Deputy Director, Web Science Research Center (RPI)
http://tw.rpi.edu olyerickson@gmail.com
Twitter & Skype: olyerickson

**Comment by mrpatrickwest** [comment]
Repository is used for query and xslt in creating dynamic drupal pages.
